### ISSUE TITLE
Exercises description at `https://typescript-exercises.github.io/` vs on the `master` branch

### ISSUE THREAD

**Issue by domanskaanna** [typescript-exercises/typescript-exercises#107]
I've started following exercises at `https://typescript-exercises.github.io/`, and I discovered that some links in the exercises description were deprecated. I wanted to create a pull request and fix them, but I found that everything is already fixed on the master branch.

**Comment by mdevils** [comment]
Hello @domanskaanna,

Thank you for noticing. I've updated the website, can you please check again?

I should probably automate this :)

**Comment by domanskaanna** [comment]
@mdevils all good now! Thank you for fixing it :)
