### ISSUE TITLE
Cannot collapse side menu or error section

### ISSUE THREAD

**Issue by dmtri** [typescript-exercises/typescript-exercises#114]
I'm having trouble collapsing the side menu and error section on typescript-exercises.github.io. I tried clicking on the highlighted buttons but it didn't work.
![image](https://user-images.githubusercontent.com/11147211/193413683-dfac773f-bf7a-4e43-94dd-839f447fb80c.png)

Browser: Version 106.0.5249.91 on MacOS Ventura (Incognito)

**Comment by mdevils** [comment]
Hello @dmtri .

Sorry for a huge delay in the response. The issue was fixed and deployed.

Thanks for reporting.

**Comment by dmtri** [comment]
thanks for your help @mdevils , really appreciate it!
