### ISSUE TITLE
Exercise 14 contains no test case with multiple sorts

### ISSUE THREAD

**Issue by fabb** [typescript-exercises/typescript-exercises#20]
The exercise description of exercise 14 defines that `sort` can have a format like this: `{fieldName1: 1 | -1, fieldName2: 1 | -1, ...}`. But the test cases always just sort by a single field.

**Comment by mdevils** [comment]
Good, point, thanks. I ended up discarding this exercise and replacing with another one. Check out the new interactive version of these exercises! https://typescript-exercises.github.io/
