### ISSUE TITLE
tsconfig.json 'esModuleInterop'

### ISSUE THREAD

**Issue by Z-HNAN** [typescript-exercises/typescript-exercises#22]
in exercise, we use `import chalk from 'chalk'`
but this module use commonJS, VSCode warning this problem

we need add this compilerOptions
```js
{
  "compilerOptions": {
    // ...
    "esModuleInterop": true,
  }
}

```

**Comment by mdevils** [comment]
Thank you for raising this. It is not an issue anymore since the exercises are now interactive and available for everyone here: https://typescript-exercises.github.io/. Any feedback is welcome.
