### ISSUE TITLE
Exercise 11 and 12 complain about duplicate declarations

### ISSUE THREAD

**Issue by pvinis** [typescript-exercises/typescript-exercises#26]

**Comment by mdevils** [comment]
Hello @pvinis,

Can you please a bit more specific here?

**Comment by pvinis** [comment]
Even when I copied the solution in `index.d.ts` on exercise 11, I got ts errors.
<img width="669" alt="Screenshot 2020-08-14 at 15 56 43" src="https://user-images.githubusercontent.com/100233/90256957-c73d9400-de46-11ea-8de8-24c24c4b8153.png">

**Comment by mdevils** [comment]
@pvinis Managed to reproduce this, thank you.

The fix (a332442b32d2fb5e177a5031594aa47810267a9d) was merged and the website was redeployed.

Please check it out.

**Comment by pvinis** [comment]
Thanks for the quick response! (Can't test it right now, I'm on a different computer so I would have to do all again :p I'll test it later on my other one.)
