### ISSUE TITLE
Minor copy changes and suggestions

### ISSUE THREAD

**Issue by miamollie** [typescript-exercises/typescript-exercises#28]
Hi there,

Firstly, I loved working through these exercises, what a great repo and interactive tool you've built! 

There are a few places where the English could be very slightly improved, and some grammatical errors. I've got a branch of copy suggestions ready, if you're willing to give me permission I'll open a PR.

Thanks again for the awesome repo!

**Comment by mdevils** [comment]
Hello @miamollie. Glad you liked it. If you are still interested, you can fork this repo and create a pull-request from it to this one. You don't need permissions to do it.
