### ISSUE TITLE
Confused about alternate solution for exercice 8

### ISSUE THREAD

**Issue by vjau** [typescript-exercises/typescript-exercises#30]
The recommended solution for exercice 8 is to write :
```ts
type PowerUser = Omit<User, 'type'> & Omit<Admin, 'type'> & {
    type: 'powerUser'
};
```
I had written this solution, which seems more DRY and works in the online game
```ts
type PowerUser = Omit<User & Admin, "type"> & {
   type: "powerUser"
};
```
So i tried to submit it as a pull request, but i'm unable to get it to work locally.
The compiler is interpreting PowerUser as
```ts
Pick<never, string|number|symbol> & {
   type:"powerUser"
};
```

I then figured out that type of `User & Admin` is `never` because they have no intersection (type can't be both "user" and "admin" at the same time), so Typescript is in fact clever here. 

But then why is the online game accepting my solution ? Is it TS version specific ? If so, shouldn't the compiler used be upgraded ?

**Comment by mdevils** [comment]
Hello, @vjau! Yes, it's version specific and this behavior was changed in later versions.
