### ISSUE TITLE
Feedback for exercises

### ISSUE THREAD

**Issue by andrewgreenh** [typescript-exercises/typescript-exercises#6]
Hello!

I streamed my solution process to twitch. In total, it took me around 3 hours I think.
I really enjoyed the exercises and had a lot of fun working on the harder ones.

As you asked for feedback in the README, here are some points:

- **Use a test runner for the tests** right now, you only ever get one error message on the console and it is formatted quite poorly (it's just stringified on the console). Something like jest would better show you the results and the percentage of passed/failing tests.
- **More granular tests** that is regarding exercises 13,14 and 15. I completed 14 with some bugs left in the sort options. More fine grained tests, testing all features of the interface would prevent these problems
- **Add tests for types** with several TypeScript helper functions, you could add tests for the types itself, so that return types could be better checked. See this article for reference: https://2ality.com/2019/07/testing-static-types.html
- **type safety for the projection field**: We could get better type safety when we change the interface from receiving and object with "1" in all keys that we want to retain, to an array of keys. That way we could use the "Pick" type to return the reduced type from the find method. I tried implementing that with the current interface but could not get that working.

As I said, I hat lots of fun during this challenge! Huge props to you :)

Best regards.

**Comment by kubk** [comment]
I suggest this library to test types: https://github.com/dsherret/conditional-type-checks

Usage:
```typescript
import { assert, IsExact } from "conditional-type-checks";

const result = someFunction(someArg);

// compile error if the type of `result` is not exactly `string | number`
assert<IsExact<typeof result, string | number>>(true);
```

**Comment by mdevils** [comment]
Interesting. Thank you for the feedback, I'll consider it.

**Comment by mdevils** [comment]
Interactive version is implemented and published: https://typescript-exercises.github.io/. This includes automatic type-tests. Thank you for your idea!
